{% set version = '0.2.3' %}
{% set posix = 'm2-' if win else '' %}
{% set native = 'm2w64-' if win else '' %}

package:
  name: r-functiondepends
  version: {{ version|replace("-", "_") }}

source:
  url:
    - {{ cran_mirror }}/src/contrib/functiondepends_{{ version }}.tar.gz
    - {{ cran_mirror }}/src/contrib/Archive/functiondepends/functiondepends_{{ version }}.tar.gz
  sha256: 9618e9005bd962da2405919e1d3bb824bc521f1120995c99cdab0544510c035d

build:
  merge_build_host: True  # [win]
  number: 0
  noarch: generic
  rpaths:
    - lib/R/lib/
    - lib/
  missing_dso_whitelist:
    - '*/R.dll'        # [win]
    - '*/Rblas.dll'    # [win]
    - '*/Rlapack.dll'  # [win]

requirements:
  build:
    - {{ posix }}zip               # [win]
    - cross-r-base {{ r_base }}    # [build_platform != target_platform]
  host:
    - r-base
    - r-dplyr >=1.0.1
    - r-magrittr >=1.5
    - r-purrr >=0.3.4
    - r-stringr >=1.4.0
    - r-tibble >=3.0.3
    - r-tidyr >=1.1.1
    - r-tidyselect >=1.1.0
  run:
    - r-base
    - r-dplyr >=1.0.1
    - r-magrittr >=1.5
    - r-purrr >=0.3.4
    - r-stringr >=1.4.0
    - r-tibble >=3.0.3
    - r-tidyr >=1.1.1
    - r-tidyselect >=1.1.0

test:
  commands:
    - $R -e "library('functiondepends')"           # [not win]
    - "\"%R%\" -e \"library('functiondepends')\""  # [win]

about:
  home: https://CRAN.R-project.org/package=functiondepends
  license: MIT
  summary: 'Find functions in an unstructured directory and explore their dependencies. Sourcing
    of R source files is performed without side-effects: from R scripts that have executable
    code and function definitions only functions are sourced.'
  license_family: MIT
  license_file:
    - '{{ environ["PREFIX"] }}/lib/R/share/licenses/MIT'
    - LICENSE

extra:
  recipe-maintainers:
    - conda-forge/r
    - thewchan

# Package: functiondepends
# Type: Package
# Title: Find Functions and their Dependencies
# Version: 0.2.3
# Authors@R: person( "Jakub", "Sobolewski", email = "jakupsob@gmail.com", role = c("aut", "cre"))
# Description: Find functions in an unstructured directory and explore their dependencies. Sourcing of R source files is performed without side-effects: from R scripts that have executable code and function definitions only functions are sourced.
# License: MIT + file LICENSE
# Encoding: UTF-8
# Suggests: testthat, covr, knitr, rmarkdown, ggplot2, igraph
# Imports: dplyr (>= 1.0.1), tidyr (>= 1.1.1), stringr (>= 1.4.0), purrr (>= 0.3.4), magrittr (>= 1.5), tibble (>= 3.0.3), tidyselect (>= 1.1.0)
# RoxygenNote: 7.1.1
# VignetteBuilder: knitr
# Depends: R (>= 2.10)
# NeedsCompilation: no
# Packaged: 2022-02-21 18:45:34 UTC; jakub
# Author: Jakub Sobolewski [aut, cre]
# Maintainer: Jakub Sobolewski <jakupsob@gmail.com>
# Repository: CRAN
# Date/Publication: 2022-02-21 19:00:05 UTC
